### ISSUE TITLE
Use `electron_config_cache` env var to search for cached downloads

### ISSUE THREAD

**Issue by gasinvein** [electron/get#160]
Electron docs [say](https://github.com/electron/electron/blob/master/docs/tutorial/installation.md#cache) that one can override path to cached electron downloads via the `electron_config_cache` environment variable, but it doesn't seem to be the case with electron-get - the env var is ignored and, as far as I understand, cache path is unconditionally resolved to something like `$XDG_CACHE_HOME/electron/sanitazed_url/electron.zip`:
https://github.com/electron/get/blob/f2c625377c758c8348a5432e22a5a9ac0ef98889/src/Cache.ts#L17-L22
`electron-downoad` did respect `electron_config_cache`.

**Comment by shiftkey** [comment]
@gasinvein `cacheRoot` is the parameter in `@electron/get` that you can control, and you can see it is used in the Electron `install.js` script:

https://github.com/electron/electron/blob/35455c725d76a00f0d1ddf331497e250e4d19a55/npm/install.js#L22-L32

```js
downloadArtifact({
  version,
  artifactName: 'electron',
  force: process.env.force_no_cache === 'true',
  cacheRoot: process.env.electron_config_cache,
  platform: process.env.npm_config_platform || process.platform,
  arch: process.env.npm_config_arch || process.arch
}).then(extractFile).catch(err => {
  console.error(err.stack);
  process.exit(1);
});
```

On Linux I think these environment variables are case sensitive (`ELECTRON_CACHE_CONFIG` didn't work for me but `electron_cache_config` did), and I was able to control the cache location like this:

```
# clear out the local Electron files to force retrieval
$ rm -rf ./node_modules/electron/dist                                                      
$ electron_config_cache=/opt/electron/cache DEBUG=* node ./node_modules/electron/install.js
  @electron/get:index Checking the cache for electron-v9.3.1-linux-x64.zip (https://github.com/electron/electron/releases/download/v9.3.1/electron-v9.3.1-linux-x64.zip) +1ms
  @electron/get:index Cache miss +1ms
  @electron/get:index Downloading https://github.com/electron/electron/releases/download/v9.3.1/electron-v9.3.1-linux-x64.zip to /tmp/electron-download-Gs2baZ/electron-v9.3.1-linux-x64.zip with options: undefined +18ms
  @electron/get:index Cache location: undefined +15s
  @electron/get:index Checking the cache for SHASUMS256.txt (https://github.com/electron/electron/releases/download/v9.3.1/SHASUMS256.txt) +0ms
  @electron/get:index Cache hit +1ms
  sumchecker Reading "/home/shiftkey/.cache/electron/httpsgithub.comelectronelectronreleasesdownloadv9.3.1SHASUMS256.txt/SHASUMS256.txt (binary mode: false)" +0ms
  sumchecker Parsing checksum file +1ms
  ...
  sumchecker validateFile: electron-v9.3.1-linux-x64.zip +3ms
  sumchecker Reading file with "binary" encoding +0ms
  sumchecker Expected checksum: 90f983dc4b2c5f97b27c7193b984173396b8fb37405593cad9d3a4bd666fc91d; Actual: 90f983dc4b2c5f97b27c7193b984173396b8fb37405593cad9d3a4bd666fc91d +105ms
  @electron/get:cache Moving /tmp/electron-download-Gs2baZ/electron-v9.3.1-linux-x64.zip to /opt/electron/cache/httpsgithub.comelectronelectronreleasesdownloadv9.3.1electron-v9.3.1-linux-x64.zip/electron-v9.3.1-linux-x64.zip +0ms
  ...
$  ls /opt/electron/cache 
httpsgithub.comelectronelectronreleasesdownloadv9.3.1electron-v9.3.1-linux-x64.zip
```

There's a secondary issue with the checksum not using the cache (that `Cache location: undefined` message in the debug output) but that was fixed in [`v1.7.3`](https://github.com/electron/get/releases/tag/v1.7.3). I've also spotted an issue with electron-chromedriver not looking for a cache that should be a small PR to address.

**Comment by gasinvein** [comment]
Aha, so it probably the cache issue caused electron/get to keep hitting network on my side regardless of cache. Sorry for misreport, then.

**Comment by shiftkey** [comment]
@gasinvein feel free to close this out if you're able to get this working

**Comment by gasinvein** [comment]
Sorry, I didn't get my hands on testing this again. I'll reopen the issue if the problem pops up with recent electron/get.

**Comment by CMCDragonkai** [comment]
I've noticed that the cache file structure is different from documented now. Has something changed? And how do we know what hash we should be using?

```
»» ~/.cache/electron
 ♖ tree .                                                                                                                             ⚡(master) pts/13 22:07:56
.
└── feb47dbabb4228432601f47434efa16e7c28d354e7f7c18a1ae85ff5586cf209
    ├── electron-v12.0.0-linux-x64.zip
    ├── electron-v12.0.0-win32-x64.zip
    └── SHASUMS256.txt

1 directory, 3 files
```

**Comment by gasinvein** [comment]
@CMCDragonkai It's a hash of full download URL up the first parent directory, e.g. `https://github.com/electron/electron/releases/download/v9.4.4`.

**Comment by CMCDragonkai** [comment]
Does the old cache structure still work?

**Comment by gasinvein** [comment]
I think no.

**Comment by CMCDragonkai** [comment]
I just tried:

```
> sha256sum <<<"https://github.com/electron/electron/releases/download/v12.0.0"
3f4908d572eab75fee86c50bf6139ac28778080cebce443c7deaaca7d53b97ff  -
```

This hash is not `feb47dbabb4228432601f47434efa16e7c28d354e7f7c18a1ae85ff5586cf209` as stated in `~/.cache/electron`.

**Comment by CMCDragonkai** [comment]
Oh I see now:

```
> crypto.createHash('sha256').update('https://github.com/electron/electron/releases/download/v12.0.0').digest('hex');
'feb47dbabb4228432601f47434efa16e7c28d354e7f7c18a1ae85ff5586cf209'
```

**Comment by CMCDragonkai** [comment]
I'm actually trying to be able to do this the command line. Any ideas how to use sha256sum or something else to get the equivalent hash?

**Comment by CMCDragonkai** [comment]
Ok I got it:

```
> printf 'https://github.com/electron/electron/releases/download/v12.0.0' | sha256sum | cut -f1 -d' '
feb47dbabb4228432601f47434efa16e7c28d354e7f7c18a1ae85ff5586cf209
```

**Comment by CMCDragonkai** [comment]
I've tried to create the cache:

```
»» /nix/store/7jdnvyv96fhx7r5c00i37v9j2bdznqpk-electron-builds-cache
 ♜ tree .                                                                                                  pts/10 2:28:29
.
├── feb47dbabb4228432601f47434efa16e7c28d354e7f7c18a1ae85ff5586cf209
│   ├── electron-v12.0.0-linux-x64.zip -> /nix/store/xhwabh8zv7hjcmhq6ii2nhnzyynll6cv-electron-v12.0.0-linux-x64.zip
│   ├── electron-v12.0.0-win32-x64.zip -> /nix/store/vwaii5f4740c4wzn5qwk62ql1wjdqm37-electron-v12.0.0-win32-x64.zip
│   └── SHASUMS256.txt -> /nix/store/a7madm9y32gixss7dinzf2k0wd1v7b8q-SHASUMS256.txt
├── httpsgithub.comelectronelectronreleasesdownloadv12.0.0electron-v12.0.0-linux-x64.zip
│   └── electron-v12.0.0-linux-x64.zip -> /nix/store/xhwabh8zv7hjcmhq6ii2nhnzyynll6cv-electron-v12.0.0-linux-x64.zip
└── httpsgithub.comelectronelectronreleasesdownloadv12.0.0SHASUMS256.txt
    └── electron-v12.0.0-win32-x64.zip -> /nix/store/vwaii5f4740c4wzn5qwk62ql1wjdqm37-electron-v12.0.0-win32-x64.zip

3 directories, 5 files
```

But I still get the same error:

```
⠋ Checking your system⠙ Checking your system⠹ Checking your system✔ Checking your system
⠋ Resolving Forge Config✔ Resolving Forge Config
We need to package your application before we can make it
⠋ Preparing to Package Application for arch: x64
An unhandled rejection has occurred inside Forge:
GotError [RequestError]: getaddrinfo ENOTFOUND github.com
    at ClientRequest.<anonymous> (/nix/store/v9mmqb4afmd4kwv7nkmnfv9v9yzqyp61-node__at_electron-forge_slash_cli-6.0.0-beta.54/lib/node_modules/@electron-forge/cli/node_modules/@electron/get/node_modules/got/source/request-as-event-emitter.js:178:14)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:327:22)
    at ClientRequest.EventEmitter.emit (domain.js:467:12)
    at ClientRequest.origin.emit (/nix/store/v9mmqb4afmd4kwv7nkmnfv9v9yzqyp61-node__at_electron-forge_slash_cli-6.0.0-beta.54/lib/node_modules/@electron-forge/cli/node_modules/@electron/get/node_modules/@szmarczak/http-timer/source/index.js:37:11)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket.EventEmitter.emit (domain.js:467:12)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'ENOTFOUND',
  host: 'github.com',
  hostname: 'github.com',
  method: 'GET',
  path: '/electron/electron/releases/download/v12.0.0/electron-v12.0.0-linux-x64.zip',
  socketPath: undefined,
  protocol: 'https:',
  url: 'https://github.com/electron/electron/releases/download/v12.0.0/electron-v12.0.0-linux-x64.zip',
  gotOptions: {
    path: '/electron/electron/releases/download/v12.0.0/electron-v12.0.0-linux-x64.zip',
    protocol: 'https:',
    slashes: true,
    auth: null,
    host: 'github.com',
    port: null,
    hostname: 'github.com',
    hash: null,
    search: null,
    query: null,
    pathname: '/electron/electron/releases/download/v12.0.0/electron-v12.0.0-linux-x64.zip',
    href: 'https://github.com/electron/electron/releases/download/v12.0.0/electron-v12.0.0-linux-x64.zip',
    retry: {
      retries: [Function (anonymous)],
      methods: [Set],
      statusCodes: [Set],
      errorCodes: [Set]
    },
    headers: {
      'user-agent': 'got/9.6.0 (https://github.com/sindresorhus/got)',
      'accept-encoding': 'gzip, deflate'
    },
    hooks: {
      beforeRequest: [],
      beforeRedirect: [],
      beforeRetry: [],
      afterResponse: [],
      beforeError: [],
      init: []
    },
    decompress: true,
    throwHttpErrors: true,
    followRedirect: true,
    stream: true,
    form: false,
    json: false,
    cache: false,
    useElectronNet: false,
    method: 'GET'
  }
}

Electron Forge was terminated. Location:
{}
```

My build environment doesn't allow any network access at all, is there a way to debug why it's not making use of the cache? I'm using `electron_config_cache=...`, ` force_no_cache="false"` and `ELECTRON_SKIP_BINARY_DOWNLOAD="1"`.

**Comment by CMCDragonkai** [comment]
After using `DEBUG=*` I can see an interesting logs:

```
  @electron/get:index Checking the cache (undefined) for electron-v12.0.0-linux-x64.zip (https://github.com/electron/electron/releases/download/v12.0.0/electron-v12.0.0-linux-x64.zip) +0ms
  @electron/get:index Cache miss +2ms
  @electron/get:index Downloading https://github.com/electron/electron/releases/download/v12.0.0/electron-v12.0.0-linux-x64.zip to /build/electron-download-I9H7r9/electron-v12.0.0-linux-x64.zip with options: undefined +19ms
```

It has a cache miss even though I put everything in the cache.

Is there a way to find out where this cache is? And also why there's `(undefined)` above?

**Comment by CMCDragonkai** [comment]
The message above corresponds to this line: https://github.com/electron/get/blob/v1.12.4/src/index.ts#L71

We are using 1.12.4.

Which means `artifactDetails.cacheRoot` is `undefined`.

What could cause that to be `undefined`?

**Comment by CMCDragonkai** [comment]
The problem is this...

The `electron-packager` exposes a `packager` default export. This is used by `electron-forge` in the `packages/api/core/src/api/package.ts`.

Specifically where it calls `const outputPaths = await packager(packageOpts);`. Through several series of magic, it will eventually call the `downloadArtifact` function in `@electron/get`.

At no point is the `cacheRoot` ever acquired from an environment variable.

The `packageOpts` defined in `packages/api/core/src/api/package.ts` has no mention about download options that would specify the `cacheRoot`.

So currently there is **no** way to set the `cacheRoot` in the latest `electron-forge`.

**Comment by musjj** [comment]
So you can't override the `cacheRoot`, but it should still be looking for the cache in `~/.cache/electron` right?
In my build process, I did something like:
```bash
export HOME=$(mktemp -d)
mkdir -p $HOME/.cache/electron
...
```

This is the directory structure of the cache:

```
/build/tmp.9BugPE5gLX/.cache/electron
`-- c05e30a4410a1f0cea42684a86b42fafa64de3219611f15aca637d59c874de23
    |-- SHASUMS256.txt
    `-- electron-v8.5.5-linux-x64.zip
```

But I still can't get it to pick up the cache. Am I doing something wrong here?
