### ISSUE TITLE
Can't commit

### ISSUE THREAD

**Issue by joaomoreno** [electron/get#187]
After cloning and running `yarn`, I can't make a commit since the `husky` script fails with:

```
> git -c user.useConfigOnly=true commit --quiet --allow-empty-message --file -
husky > pre-commit (node v14.15.1)
/home/codespace/workspace/get/node_modules/any-observable/register.js:29
		throw new Error('Cannot find any-observable implementation nor' +
		^

Error: Cannot find any-observable implementation nor global.Observable. You must install polyfill or call require("any-observable/register") with your preferred implementation, e.g. require("any-observable/register")('rxjs') on application load prior to any require("any-observable").
    at loadImplementation (/home/codespace/workspace/get/node_modules/any-observable/register.js:29:9)
    at /home/codespace/workspace/get/node_modules/any-observable/loader.js:30:18
    at Object.<anonymous> (/home/codespace/workspace/get/node_modules/any-observable/index.js:2:39)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/codespace/workspace/get/node_modules/@samverschueren/stream-to-observable/index.js:2:20)
husky > pre-commit hook failed (add --no-verify to bypass)
```

**Comment by MarshallOfSound** [comment]
This looks like an incompatible node version in codespaces, try updating node?  Otherwise raise the issue with husky rather than here 😄
